name: Dynamically Build and test .NET Projects

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.project.project-name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
        project:
          - project-name: app-dotnet-01
            app-dir: 03-app-dotnet/03-app-dotnet.csproj
          - project-name: app-dotnet-02
            app-dir: 04-app-dotnet/04-app-dotnet.csproj

    steps:
      - name: Checkout Code (github-actions-course)
        uses: actions/checkout@v4

      - name: Checkout Shared GitHub Actions Repo
        uses: actions/checkout@v4
        with:
          repository: ukhare/github-actions
          path: .github/actions/shared
          token: ${{ secrets.GH_PAT }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build ${{ matrix.project.project-name }}
        uses: ./.github/actions/shared/.github/actions/dotnet-build-action
        with:
          project-name: ${{ matrix.project.project-name }}
          app-dir: ${{ matrix.project.app-dir }}
          build-configuration: Release
          upload_build: true
